Training Progress:   0%|                                                                                                                                     | 0/6200 [00:10<?, ?it/s]
ITER:  0
Traceback (most recent call last):                                                                                                                                                    
saving checkpoint to out
  File "/data/Bhashathon/train.py", line 472, in <module>
    wandb.log("loss/iter",lossf)
  File "/data/miniconda/envs/aws_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda/envs/aws_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda/envs/aws_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda/envs/aws_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1873, in log
    self._log(data=data, step=step, commit=commit)
  File "/data/miniconda/envs/aws_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1582, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
